# Placeholder memory map for Mario Kart DS.
# Replace the addr values with correct addresses for your ROM build.
# size: 1|2|4 bytes. little_endian: true|false. signed: true|false. scale: optional float multiplier.

progress:
  addr: 0x0234E160
  size: 4
  little_endian: true
  signed: false
  #scale: 0.1


speed:
  # Likely speed 
  addr: 0x0217AD10
  size: 2
  little_endian: true
  signed: false
  # Scale 2-byte speed down to keep reward from clipping (tunable)
  scale: 0.01

collisions:
  # Wall collisions counter
  addr: 0x023525D0
  size: 1
  little_endian: true
  signed: false


wrong_way:
  # Mapped to 'Wrong Way' flag for now
  addr: 0x0217B8C4
  size: 1
  little_endian: true
  signed: false


lap:
  # 0x0217B85C â€” Likely lap
  addr: 0x0217B85C
  size: 1
  little_endian: true
  signed: false



