rom_path: "ROM/mariokart.nds"
savestate_path: "ROM/yoshi_falls_time_trial.dsv"

frames_per_step: 4
max_steps_per_episode: 2000

# Memory addresses (to be filled after reverse engineering / notebook work)
lap_addr: null
speed_addr: null
progress_addr: null

# Additional state configuration
use_timer: false
extra_addrs: {}


